FROM node:15-alpine As development

WORKDIR /app

COPY package*.json ./
COPY yarn.lock .

RUN yarn --only=development

COPY . .

RUN yarn build

FROM node:15-alpine As production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app

COPY package*.json ./
COPY yarn.lock .

RUN yarn --only=production

COPY . .

COPY --from=development /app/dist ./dist

CMD ["node", "dist/main"]
