apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbase-authentication-depl
spec:
  selector:
    matchLabels:
      app: cloudbase-authentication-depl
  template:
    metadata:
      labels:
        app: cloudbase-authentication-depl
    spec:
      containers:
        - name: cloudbase-authentication-depl
          image: vnavaneeth/cloudbase-authentication
          imagePullPolicy: "Never"
          resources:
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
          # ports:
          # - containerPort: <Port>

---
apiVersion: v1
kind: Service
metadata:
  name: cloudbase-authentication-svc
spec:
  selector:
    app: cloudbase-authentication-depl
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
